app:
  handler: wsgi_handler.handler
  layers:
  - arn:aws:lambda:us-east-1:464889327419:layer:flask:5
  events:
    - http:
        path: /
        method: get
        cors:
          origin: '*'
    - http:
        path: /users
        method: get
        cors:
          origin: '*'
